name: Test, build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: nats-adminportal-dc # set this to the name of your Azure Web App
  SERVER_PATH: "src/vite-api.Tests/bin/Debug/net7.0/config"
  DOTNET_PATH: "src/vite-api.Tests"
  DOTNET_VERSION: "7.0.x"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start local NATS server
        working-directory: ${{ env.SERVER_PATH }}
        shell: pwsh
        run: |
          Start-Process -NoNewWindow -FilePath ".\nats-server.exe" -ArgumentList "-c .\server.conf"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: run unit tests
        working-directory: ${{ env.DOTNET_PATH }}
        run: |
          dotnet test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          secrets: |
            "NATS_SERVER_URL=${{ secrets.NATS_SERVER_URL }}"
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_NATS_ADMINPORTAL_PUBLISH_PROFILE }}
          images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
